blank_issues_enabled: false
contact_links:
  - name: Guides
    url: https://trash-guides.info/
    about: Guides mainly for Sonarr/Radarr/Bazarr and everything related to it.
  - name: Discord Support
    url: https://discord.gg/Vau8dZ3
    about: Ask questions and any other related help
